using UnityEngine;

namespace SugarRush
{
    /// <summary>
    /// The playable racers: prefab, display data and the 0..1 stat values shown in the menu.
    /// Generated by the Sugar Rush builder.
    /// </summary>
    public class KartRoster : ScriptableObject
    {
        [System.Serializable]
        public class Entry
        {
            public string id;
            public string displayName;
            public GameObject prefab;
            [Tooltip("Online variant of the prefab (NetworkObject + NetKart).")]
            public GameObject netPrefab;
            public Color color = Color.white;
            [Range(0, 1)] public float speed;
            [Range(0, 1)] public float acceleration;
            [Range(0, 1)] public float handling;
            [Tooltip("How this character drives when the computer controls it.")]
            public AIPersonality personality;
            [Tooltip("Standing character model for the menu, selection and podium (none = use the portrait).")]
            public GameObject character;
            [Tooltip("2D portrait, shown as a cut-out when there is no 3D character yet.")]
            public Texture2D portrait;
        }

        public Entry[] karts;

        public Entry Get(int index) => karts[((index % karts.Length) + karts.Length) % karts.Length];
    }

    public static class SceneNames
    {
        public const string MainMenu = "MainMenu";
        public const string Race = "SugarRush_Track";
    }
}
