using UnityEngine;

namespace SugarRush
{
    /// <summary>
    /// The playable racers: prefab, display data and the 0..1 stat values shown in the menu.
    /// Generated by the Sugar Rush builder.
    /// </summary>
    public class KartRoster : ScriptableObject
    {
        [System.Serializable]
        public class Entry
        {
            public string id;
            public string displayName;
            public GameObject prefab;
            public Color color = Color.white;
            [Range(0, 1)] public float speed;
            [Range(0, 1)] public float acceleration;
            [Range(0, 1)] public float handling;
            [Tooltip("How this character drives when the computer controls it.")]
            public AIPersonality personality;
        }

        public Entry[] karts;

        public Entry Get(int index) => karts[((index % karts.Length) + karts.Length) % karts.Length];
    }

    public static class SceneNames
    {
        public const string MainMenu = "MainMenu";
        public const string Race = "SugarRush_Track";
    }
}
