using UnityEngine;

namespace SugarRush
{
    /// <summary>
    /// Every race track: its id (records), its scene (one race scene per track, all generated by
    /// the Sugar Rush builder) and the Loc key of its name. Index 0 is the original circuit.
    /// </summary>
    public static class Tracks
    {
        public readonly struct Info
        {
            public readonly string Id, Scene, NameKey;
            public Info(string id, string scene, string nameKey) { Id = id; Scene = scene; NameKey = nameKey; }
            public string DisplayName => Loc.T(NameKey);
        }

        public static readonly Info[] All =
        {
            new("sugar_rush", SceneNames.Race, "track.sugarRush"),
            new("gummy_forest", "GummyForest_Track", "track.gummyForest"),
        };

        public static int Count => All.Length;

        public static Info Get(int index) => All[Wrap(index)];

        public static int Wrap(int index) => ((index % Count) + Count) % Count;

        /// <summary>The track chosen in the menu (single player and split screen; online the host's pick).</summary>
        public static Info Selected => Get(GameSettings.Track);

        public static bool IsRaceScene(string scene)
        {
            foreach (var t in All)
                if (t.Scene == scene) return true;
            return false;
        }

        /// <summary>Index of the track whose scene is loaded, or 0.</summary>
        public static int IndexOfScene(string scene)
        {
            for (int i = 0; i < All.Length; i++)
                if (All[i].Scene == scene) return i;
            return 0;
        }

        public static int Next(int current, int direction) => Wrap(current + (direction == 0 ? 0 : (int)Mathf.Sign(direction)));
    }
}
